# Generated by Django 3.1 on 2021-05-07 07:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.TextField(db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField()),
                ('author', models.TextField()),
                ('title', models.TextField()),
                ('statement', models.TextField()),
                ('difficulty', models.TextField()),
                ('source', models.TextField(null=True)),
                ('sample_test', django.contrib.postgres.fields.jsonb.JSONField()),
                ('testset_dir', models.TextField()),
                ('testset_count', models.PositiveIntegerField()),
                ('time_limit', models.IntegerField()),
                ('memory_limit', models.IntegerField()),
                ('total_submission', models.BigIntegerField(default=0)),
                ('correct_submission', models.BigIntegerField(default=0)),
                ('statistic_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('tags', models.ManyToManyField(to='problem.ProblemTag')),
            ],
            options={
                'db_table': 'problem',
                'ordering': ['created'],
            },
        ),
    ]
