# Generated by Django 3.2.5 on 2021-08-13 09:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.file_upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.TextField()),
            ],
            options={
                'db_table': 'problemtag',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.CharField(db_index=True, max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-z]*$', 'Only lowercase alphanumeric characters are allowed.')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True, null=True)),
                ('title', models.TextField()),
                ('statement', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=50)),
                ('source', models.TextField(null=True)),
                ('sample_test', models.JSONField(blank=True, default=dict, null=True)),
                ('test_zip', models.FileField(blank=True, default=None, null=True, upload_to=utils.file_upload.FileUploadUtils._wrapper)),
                ('time_limit', models.IntegerField(default=1000)),
                ('memory_limit', models.IntegerField(default=256)),
                ('total_submission', models.BigIntegerField(default=0)),
                ('correct_submission', models.BigIntegerField(default=0)),
                ('statistic_info', models.JSONField(default=dict)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='problem.ProblemTag')),
            ],
            options={
                'db_table': 'problem',
                'ordering': ['-id'],
            },
        ),
    ]
