# Generated by Django 3.2.2 on 2021-06-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemtag',
            old_name='tagName',
            new_name='tag_name',
        ),
    ]
