# Generated by Django 3.1 on 2021-05-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20210507_1456'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='problemtag',
            table='problemtag',
        ),
    ]
