# Generated by Django 3.2.4 on 2021-07-19 08:56

import django.core.validators
from django.db import migrations, models
import utils.file_upload


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20210615_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='testset_count',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='testset_dir',
        ),
        migrations.AddField(
            model_name='problem',
            name='test_zip',
            field=models.FileField(blank=True, default=None, null=True, upload_to=utils.file_upload.FileUploadUtils._wrapper),
        ),
        migrations.AlterField(
            model_name='problem',
            name='display_id',
            field=models.CharField(db_index=True, max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-z]*$', 'Only lowercase alphanumeric characters are allowed.')]),
        ),
    ]
