# Generated by Django 3.1 on 2021-05-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20210507_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50),
        ),
    ]
