# Generated by Django 3.1 on 2021-05-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20210507_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_test',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='testset_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='testset_dir',
            field=models.TextField(null=True),
        ),
    ]
