# Generated by Django 3.1 on 2021-05-07 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20210508_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='statistic_info',
        ),
    ]
