# Generated by Django 3.1 on 2021-05-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_problem_statistic_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='sample_test',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
