# Generated by Django 3.1 on 2021-05-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
        ('accounts', '0003_auto_20210516_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='solved_problem',
            field=models.ManyToManyField(blank=True, to='problem.Problem'),
        ),
    ]
