# Generated by Django 3.1 on 2021-06-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210605_1530'),
        ('accounts', '0008_alter_user_profile_pic'),
    ]

    operations = [
    ]
