# Generated by Django 3.2.4 on 2021-06-15 09:22

from django.db import migrations, models
import utils.file_upload


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210615_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avatar/__default__.png', null=True, upload_to=utils.file_upload.FileUploadUtils._wrapper),
        ),
    ]
