# Generated by Django 3.2.4 on 2021-06-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_user_profile_pic'),
        ('accounts', '0027_auto_20210615_1835'),
    ]

    operations = [
    ]
