# Generated by Django 3.2.5 on 2021-08-13 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(null=True)),
                ('language', models.CharField(choices=[('Python3', 'PyPy3'), ('Python2', 'Python3'), ('Java', 'Python2'), ('C', 'Java'), ('Cpp', 'C')], default='PyPy3', max_length=50)),
                ('verdict', models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compile Error'), ('REJECT', 'Rejected'), ('SE', 'System Error'), ('WAIT', 'Waiting'), ('JUDGE', 'Judging'), ('REJUDGE', 'Rejudging'), ('NEW', 'New')], default='New', max_length=128)),
                ('output', models.JSONField(default=dict)),
                ('time', models.IntegerField(null=True)),
                ('memory', models.IntegerField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
            ],
            options={
                'db_table': 'submission',
                'ordering': ['id', 'submit_time'],
            },
        ),
    ]
