# Generated by Django 3.1 on 2021-05-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('Python3', 'PyPy3'), ('Python2', 'Python3'), ('Java', 'Python2'), ('C', 'Java'), ('C++', 'C')], default='PyPy3', max_length=50),
        ),
    ]
