# Generated by Django 3.1 on 2021-05-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='verdict_code',
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compile Error'), ('SE', 'System Error'), ('WAIT', 'Waiting'), ('JUDGE', 'Judging'), ('NEW', 'New')], default='New', max_length=20),
        ),
    ]
