# Generated by Django 3.1 on 2021-05-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20210519_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('Python3', 'PyPy3'), ('Python2', 'Python3'), ('Java', 'Python2'), ('C', 'Java'), ('Cpp', 'C')], default='PyPy3', max_length=50),
        ),
    ]
