# Generated by Django 3.2.2 on 2021-06-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20210520_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='problem',
            new_name='problem_id',
        ),
    ]
