# Generated by Django 3.2.2 on 2021-06-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20210613_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='problem_id',
            new_name='problem',
        ),
    ]
