# Generated by Django 3.2.5 on 2021-07-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20210613_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='memory',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
