# Generated by Django 3.2.5 on 2021-08-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20210722_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compile Error'), ('REJECT', 'Rejected'), ('SE', 'System Error'), ('WAIT', 'Waiting'), ('JUDGE', 'Judging'), ('REJUDGE', 'Rejudging'), ('NEW', 'New')], default='New', max_length=128),
        ),
    ]
