# Generated by Django 3.1 on 2021-05-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=256, null=True)),
                ('socketaddress', models.CharField(max_length=40)),
                ('token', models.CharField(max_length=32)),
                ('is_disabled', models.BooleanField(default=False)),
                ('judging_sub_id', models.IntegerField(default=None, null=True)),
                ('last_heartbeat', models.DateTimeField()),
                ('added_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'judge_server',
                'ordering': ['-is_disabled', '-added_time'],
            },
        ),
    ]
