# Generated by Django 3.1 on 2021-05-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runcode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='testdata',
        ),
        migrations.AddField(
            model_name='code',
            name='answer',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='code',
            name='inputs',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='code',
            name='output',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
